import * as lib from "../../../backend/sync_lib/pkg/sync_lib.js";

import createClient, { Client } from "openapi-fetch";
import type { components, paths } from "./types"; // generated by openapi-typescript
import { Logger } from "src/logger";
import { Database } from "src/database/database";
import { SyncSettings } from "src/database/sync-settings";
import {
	DocumentVersionId,
	RelativePath,
} from "src/database/document-metadata.js";

export class SyncServer {
	private static VAULT_ID = "default";
	private client: Client<paths>;

	public constructor(private database: Database) {
		this.createClient(database.getSettings());
		database.addOnSettingsChangeHandlers((s) => this.createClient(s));
	}

	private createClient(settings: SyncSettings) {
		this.client = createClient<paths>({
			baseUrl: settings.remoteUri,
		});
	}

	public async ping(): Promise<components["schemas"]["PingResponse"]> {
		const response = await this.client.GET("/ping", {
			params: {
				header: {
					authorization:
						"Bearer " + this.database.getSettings().token,
				},
			},
		});

		Logger.getInstance().info(
			"Ping response: " + JSON.stringify(response.data)
		);

		if (!response.data) {
			throw new Error(`Failed to ping server: ${response.error}`);
		}

		return response.data;
	}

	public async put({
		relativePath,
		parentVersionId,
		contentBytes,
		createdDate,
	}: {
		relativePath: RelativePath;
		parentVersionId: DocumentVersionId | undefined;
		contentBytes: Uint8Array;
		createdDate: Date;
	}): Promise<components["schemas"]["DocumentVersion"]> {
		let response = await this.client.PUT(
			"/vaults/{vault_id}/documents/{relative_path}",
			{
				params: {
					path: {
						vault_id: SyncServer.VAULT_ID,
						relative_path: encodeURIComponent(relativePath),
					},
					header: {
						authorization:
							"Bearer " + this.database.getSettings().token,
					},
				},
				body: {
					parentVersionId,
					contentBase64: lib.bytes_to_base64(contentBytes),
					createdDate: createdDate.toISOString(),
					relativePath,
				},
			}
		);

		if (!response.data) {
			throw new Error(`Failed to create document: ${response.error}`);
		}

		Logger.getInstance().info(
			"Updated document " + JSON.stringify(response.data)
		);

		return response.data;
	}

	public async delete({
		relativePath,
		createdDate,
	}: {
		relativePath: RelativePath;
		createdDate: Date;
	}): Promise<void> {
		const response = await this.client.DELETE(
			"/vaults/{vault_id}/documents/{relative_path}",
			{
				params: {
					path: {
						vault_id: SyncServer.VAULT_ID,
						relative_path: encodeURIComponent(relativePath),
					},
					header: {
						authorization:
							"Bearer " + this.database.getSettings().token,
					},
				},
				body: {
					createdDate: createdDate.toISOString(),
				},
			}
		);

		// Response will be empty if successful
		// if (!response.data) {
		// 	throw new Error(`Failed to delete document: ${response.error}`);
		// }

		Logger.getInstance().info(
			"Updated document " + JSON.stringify(response.data)
		);

		return response.data;
	}

	public async get({
		relativePath,
	}: {
		relativePath: RelativePath;
	}): Promise<components["schemas"]["DocumentVersion"]> {
		const response = await this.client.GET(
			"/vaults/{vault_id}/documents/{relative_path}",
			{
				params: {
					path: {
						vault_id: SyncServer.VAULT_ID,
						relative_path: encodeURIComponent(relativePath),
					},
					header: {
						authorization:
							"Bearer " + this.database.getSettings().token,
					},
				},
			}
		);

		if (!response.data) {
			throw new Error(`Failed to get document: ${response.error}`);
		}

		Logger.getInstance().info(
			"Get document " + JSON.stringify(response.data)
		);

		return response.data;
	}

	public async getAll(): Promise<
		components["schemas"]["DocumentVersionWithoutContent"][]
	> {
		const response = await this.client.GET("/vaults/{vault_id}/documents", {
			params: {
				path: {
					vault_id: SyncServer.VAULT_ID,
				},
				header: {
					authorization:
						"Bearer " + this.database.getSettings().token,
				},
			},
		});

		if (!response.data) {
			throw new Error(`Failed to get documents: ${response.error}`);
		}

		Logger.getInstance().info(
			"Get document " + JSON.stringify(response.data)
		);

		return response.data;
	}
}
