# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories: ["**"]
    directory: "/frontend"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories: ["**"]
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directories: ["**"]
    directory: "/backend"
    schedule:
      interval: "daily"

  # Disable this for security reasons
  # - package-ecosystem: "github-actions"
  #   directories: ["**"]
  #   schedule:
  #     interval: "daily"
