name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add clippy rustfmt
          cargo install sqlx-cli
          cd backend
          sqlx database create --database-url sqlite://db.sqlite3
          sqlx migrate run --source sync_server/src/database/migrations --database-url sqlite://db.sqlite3

      - name: Lint
        run: |
          cd backend
          cargo clippy --all-targets --all-features
          cargo fmt --all -- --check

      - name: Test
        run: |
          cd backend
          cargo test --verbose
