name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          cd backend
          cargo clippy --all-targets --all --all-features
          cargo fmt --all -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
